nse_stock_sectors = {
    'RELIANCE': 'Energy',
    'HDFCBANK': 'Financial Services',
    'INFY': 'IT',
    'ICICIBANK': 'Financial Services',
    'TCS': 'IT',
    'HINDUNILVR': 'Consumer Goods',
    'KOTAKBANK': 'Financial Services',
    'HDFC': 'Financial Services',
    'BAJFINANCE': 'Financial Services',
    'AXISBANK': 'Financial Services',
    'ASIANPAINT': 'Consumer Goods',
    'ITC': 'Consumer Goods',
    'LT': 'Infrastructure',
    'HCLTECH': 'IT',
    'SBI': 'Financial Services',
    'BAJAJFINSV': 'Financial Services',
    'TECHM': 'IT',
    'NTPC': 'Energy',
    'BANKBARODA': 'Financial Services',
    'IOC': 'Energy',
    'NESTLEIND': 'Consumer Goods',
    'ONGC': 'Energy',
    'BPCL': 'Energy',
    'POWERGRID': 'Infrastructure',
    'SBIN': 'Financial Services',
    'BHARTIARTL': 'Telecom',
    'MARUTI': 'Automobile',
    'ULTRACEMCO': 'Cement',
    'BAJAJ-AUTO': 'Automobile',
    'WIPRO': 'IT',
    'JSWSTEEL': 'Metals',
    'TATASTEEL': 'Metals',
    'HINDZINC': 'Metals',
    'SUNPHARMA': 'Pharmaceuticals',
    'TATAMOTORS': 'Automobile',
    'DMART': 'Retail',
    'BRITANNIA': 'Consumer Goods',
    'TITAN': 'Consumer Goods',
    'GAIL': 'Energy',
    'DRREDDY': 'Pharmaceuticals',
    'HINDPETRO': 'Energy',
    'CIPLA': 'Pharmaceuticals',
    'BHARTIINFR': 'Telecom',
    'EICHERMOT': 'Automobile',
    'M&M': 'Automobile',
    'ULTRACEMC': 'Cement',
    'INDUSINDBK': 'Financial Services',
    'HEROMOTOCO': 'Automobile',
    'SHREECEM': 'Cement',
    'GRASIM': 'Cement',
    'ONGCORP': 'Energy',
    'ADANIPORTS': 'Infrastructure',
    'BAJAJHLDNG': 'Financial Services',
    'DIVISLAB': 'Pharmaceuticals',
    'TATAPOWER': 'Energy',
    'ZEEL': 'Media',
    'NTPC_': 'Energy',
    'ICICIPRULI': 'Financial Services',
    'MRF': 'Automobile',
    'MOTHERSUMI': 'Automobile',
    'COALINDIA': 'Mining',
    'SBILIFE': 'Financial Services',
    'PIDILITIND': 'Consumer Goods',
    'TATACONSUM': 'Consumer Goods',
    'SBICARD': 'Financial Services',
    'DABUR': 'Consumer Goods',
    'PNB': 'Financial Services',
    'LUPIN': 'Pharmaceuticals',
    'UBL': 'Consumer Goods',
    'BHEL': 'Infrastructure',
    'ACC': 'Cement',
    'HINDALCO': 'Metals',
    'TORNTPHARM': 'Pharmaceuticals',
    'BOSCHLTD': 'Automobile',
    'DLF': 'Real Estate',
    'AMBUJACEM': 'Cement',
    'SAIL': 'Metals',
    'MUTHOOTFIN': 'Financial Services',
    'MCDOWELL-N': 'Consumer Goods',
    'PFC': 'Financial Services',
    'BEL': 'Defense',
    'BANDHANBNK': 'Financial Services',
    'PEL': 'Conglomerate',
    'TORNTPOWER': 'Energy',
    'HAVELLS': 'Consumer Goods',
    'FEDERALBNK': 'Financial Services',
    'BERGEPAINT': 'Consumer Goods',
    'RBLBANK': 'Financial Services',
    'INDIGO': 'Airlines',
    'RAMCOCEM': 'Cement',
    'EXIDEIND': 'Automobile',
    'CHOLAFIN': 'Financial Services',
    'ICICIGI': 'Financial Services',
    'BANKINDIA': 'Financial Services',
    'ADANIGREEN': 'Energy',
    'HDFCLIFE': 'Financial Services',
    'APOLLOHOSP': 'Healthcare',
    'AUROPHARMA': 'Pharmaceuticals',
    'IGL': 'Energy',
    'TVSMOTOR': 'Automobile',
    'GODREJCP': 'Consumer Goods',
    'MGL': 'Energy',
    'BATAINDIA': 'Retail',
    'M&MFIN': 'Financial Services',
    'NIACL': 'Financial Services',
    'ADANIENT': 'Conglomerate',
    'JINDALSTEL': 'Metals',
    'BANKNIFTY': 'Index',
    'COLPAL': 'Consumer Goods',
    'UBL_': 'Consumer Goods',
    'INDIANB': 'Financial Services',
    'BANKBAROD': 'Financial Services',
    'ASHOKLEY': 'Automobile',
    'SRTRANSFIN': 'Financial Services',
    'ACC_': 'Cement',
    'SIEMENS': 'Infrastructure',
    'HDFCAMC': 'Financial Services',
    'AMARAJABAT': 'Automobile',
    'BSE': 'Index',
    'MGL_': 'Energy',
    'BAJAJHLDNG_': 'Financial Services',
    'AMBUJACEM_': 'Cement',
    'BPCL_': 'Energy',
    'IDFCFIRSTB': 'Financial Services',
    'IDEA': 'Telecom',
    'PFIZER': 'Pharmaceuticals',
    'BANDHANBNK_': 'Financial Services',
    'HCLTECH_': 'IT',
    'MINDTREE': 'IT',
    'HDFCBANK_': 'Financial Services',
    'ASHOKLEY_': 'Automobile',
    'PNBHOUSING': 'Real Estate',
    'GRASIM_': 'Cement',
    'M&MFIN_': 'Financial Services',
    'PVR': 'Entertainment',
    'RPOWER': 'Energy',
    'TVTODAY': 'Media',
    'APLLTD': 'Pharmaceuticals',
    'IDBI': 'Financial Services',
    'IRCTC': 'Travel',
    'JINDALSTEL_': 'Metals',
    'L&TFH': 'Financial Services',
    'NIITTECH': 'IT',
    'INDIGO_': 'Airlines',
    'BANKINDIA_': 'Financial Services',
    'MINDACORP': 'Retail',
    'FEDERALBNK_': 'Financial Services',
    'GLENMARK': 'Pharmaceuticals',
    'TV18BRDCST': 'Media',
    'UJJIVAN': 'Financial Services',
    'CENTRALBK': 'Financial Services',
    'NCC': 'Infrastructure',
    'HDFCLIFE_': 'Financial Services',
    'SYNGENE': 'Pharmaceuticals',
    'BALKRISIND': 'Automobile',
    'CHOLAFIN_': 'Financial Services',
    'COFORGE': 'IT',
    'CRISIL': 'Financial Services',
    'DEEPAKNTR': 'Consumer Goods',
    'JUBLFOOD': 'Retail',
    'PHOENIXLTD': 'Real Estate',
    'EQUITAS': 'Financial Services',
    'LTI': 'IT',
    'RBLBANK_': 'Financial Services',
    'CANBK': 'Financial Services',
    'MOTILALOFS': 'Financial Services',
    'PNCINFRA': 'Infrastructure',
    'SUNTV': 'Media',
    'AMBER': 'Consumer Goods',
    'BLUESTARCO': 'Consumer Goods',
    'CUB': 'Financial Services',
    'GREENPLY': 'Consumer Goods',
    'KOLTEPATIL': 'Real Estate',
    'L&TFH_': 'Financial Services',
    'METROPOLIS': 'Healthcare',
    'RCOM': 'Telecom',
    'SYMPHONY': 'Consumer Goods',
    'VBL': 'Consumer Goods',
    'VENKEYS': 'Consumer Goods',
    'COROMANDEL': 'Fertilizers',
    'GODREJAGRO': 'Consumer Goods',
    'HAL': 'Defense',
    'JINDALSAW': 'Metals',
    'KEC': 'Infrastructure',
    'MINDACORP_': 'Retail',
    'NMDC': 'Metals',
    'PGHL': 'Consumer Goods',
    'PRAJIND': 'Infrastructure',
    'RITES': 'Infrastructure',
    'BANKBAROD_': 'Financial Services',
    'BATAINDIA_': 'Retail',
    'BEML': 'Infrastructure',
    'CAREERP': 'IT',
    'CENTURYTEX': 'Cement',
    'DCBBANK': 'Financial Services',
    'DHFL': 'Financial Services',
    'FSL': 'Financial Services',
    'FUTURECON': 'Retail',
    'GEPIL': 'Pharmaceuticals',
    'GESHIP': 'Shipping',
    'GUJALKALI': 'Fertilizers',
    'HATHWAY': 'Media',
    'HERCULES': 'Pharmaceuticals',
    'HEXAWARE': 'IT',
    'IDFC': 'Financial Services',
    'IDFCFIRSTB_': 'Financial Services',
    'IFCI': 'Financial Services',
    'IIFL': 'Financial Services',
    'INDIANB_': 'Financial Services',
    'IRCON': 'Infrastructure',
    'JETAIRWAYS': 'Airlines',
    'LUPIN': 'Pharmaceuticals',
    'M&M': 'Automobile',
    'MAHLOG': 'Automobile',
    'MANAPPURAM': 'Financial Services',
    'MAXFIN': 'Financial Services',
    'MCX': 'Financial Services',
    'MOTHERSUMI': 'Automobile',
    'NATCOPHARM': 'Pharmaceuticals',
    'NATIONALUM': 'Metals',
    'NH': 'Hospitality',
    'NLCINDIA': 'Power',
    'NTPC': 'Power',
    'PCJEWELLER': 'Retail',
    'PNBHOUSING': 'Financial Services',
    'PVR': 'Media',
    'RAYMOND': 'Textiles',
    'RELCAPITAL': 'Financial Services',
    'RELIANCE': 'Oil & Gas',
    'RIIL': 'Infrastructure',
    'SADBHAV': 'Infrastructure',
    'SAIL': 'Metals',
    'SCHAEFFLER': 'Automobile',
    'SFL': 'Retail',
    'SOUTHBANK': 'Financial Services',
    'SPARC': 'Pharmaceuticals',
    'SUZLON': 'Power',
    'SYNDIBANK': 'Financial Services',
    'TATAELXSI': 'IT',
    'TATAMOTORS': 'Automobile',
    'TECHM': 'IT',
    'THERMAX': 'Engineering',
    'TITAN': 'Retail',
    'TRIDENT': 'Textiles',
    'UFO': 'Media',
    'UPL': 'Chemicals',
    'VAKRANGEE': 'IT',
    'WOCKPHARMA': 'Pharmaceuticals',
    'YESBANK': 'Financial Services'
}

def get_sector_list():
    return list(set(nse_stock_sectors.values()))

def get_stock_list_by_sector(sector='IT'):
    return [key.strip()+'.NS' for key, val in nse_stock_sectors.items() if val == sector]

